kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-deployment
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-docker
          image: nicobarragan/golang:example
      volumes:
        - name: config-vol
          configMap:
            name: example-configmap

          # envFrom:
          #   configMapRef:
          #     - example-configmap
